# -*- coding: utf-8 -*-
"""loan_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VfbJKcCdrXcsSBSl9SJlsTFVUcQhV-W
"""

import numpy as np
import pandas as pd

import pandas as pd
data = pd.read_csv('bmi.csv')

data.head()

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

encoder_gender = LabelEncoder()

data['Gender'] = encoder_gender.fit_transform(data['Gender'])

print(encoder_gender.classes_,encoder_gender.transform(encoder_gender.classes_))

data.head()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = data.drop(columns='Index')
Y = data['Index']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

model = LogisticRegression(max_iter=10000)

model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

acc = accuracy_score(Y_test,Y_pred)
print(acc)

"""#downlaod model ที่สร้างไว้"""

import pickle

filename = 'loan_model.sav'
pickle.dump(model,open(filename,'wb'))

"""#นํา file model มาใช้งาน"""

loan_model = pickle.load(open('bmi_model.sav','rb'))

input_data - ([[22.0,0,4,71943.0.0,3,35000.0,4,16.02,0.49,3.0,561,0]])
prediction = bmi model.predit(input data)
if (prediction[0]==0):
  print('BMI Reject')
  else: print('BMI Accept')